version: '3.8'

services:
  db:
    build: .
    container_name: gymratz-api-db
    environment:
      POSTGRES_DB: gymratz-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: gymratz-api-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"

volumes:
  pgdata: